### ISSUE TITLE
Profile Create Phone Number Field

### ISSUE THREAD

**Issue by rer7891** [DanielEFrampton/paired-be#11]
As a visitor,
When I visit the root path, 
And I authenticate using GitHub,
I see a form that includes a phone number field which is required.
When I fill in the form and input a valid 10 digit US phone number, 
and click "Submit,"
then I'm taken to the schedule page.

When I fill in the form and input no phone number or incomplete phone number,
I am returned to the form
and I see a error message "You must provide a valid U.S. phone number."

**Comment by DanielEFrampton** [comment]
![IMG_20200219_094717](https://user-images.githubusercontent.com/40702808/74860532-11b1de00-5306-11ea-9455-effcb022645a.jpg)
