### ISSUE TITLE
Booking reminders being sent out for canceled sessions

### ISSUE THREAD

**Issue by DanielEFrampton** [DanielEFrampton/paired-be#128]

**Comment by darren2802** [comment]
not sure if this is related but I received an email that someone had booked a pairing session with me but when I log in it doesn't show any pairings coming up so a cancelation email would be useful

would also be nice if one could see more detail on the booking and cancelation emails

**Comment by DanielEFrampton** [comment]
Thanks, @darren2802! We're aware of a problem where people are being "reminded" that they have a pairing when they do not, on days where they have said they are available. We're hoping to fix it or disable it by the end of the day. Can you create a separate issue with your suggestions for the additional detail, and provide some examples? Thanks!

**Comment by darren2802** [comment]
Sure will do @DanielEFrampton!
