### ISSUE TITLE
Stats User Story

### ISSUE THREAD

**Issue by rer7891** [DanielEFrampton/paired-be#5]
As a User,
When I visit my Account Details
And I click "View Stats"
Then I should be on /stats-profile

And I should see the following:

User Name
Total Bookings (total number of paired sessions)
Total Mentor Hours (time you spent mentoring, assume 1/2 hr. sessions)
Total Hours Mentored (time you spent being mentored, assume 1/2 hr. sessions)
List of Mentees

**Comment by DanielEFrampton** [comment]
![IMG_20200218_162340](https://user-images.githubusercontent.com/40702808/74860589-268e7180-5306-11ea-9aec-2df46316ccb5.jpg)
