### ISSUE TITLE
FE Query Updates

### ISSUE THREAD

**Issue by rer7891** [DanielEFrampton/paired-be#55]
[ ] User Mutations - need to change `user: { }` to `input: { }` and wrap other mutation inputs in `input: {}`

**Comment by DanielEFrampton** [comment]
I concur with all but the first one; that's what Carleigh was referring to in the channel yesterday afternoon, which she fixed on her branch, about removing the Skill type and just sending back an array of strings. We can follow up in Slack, it was slightly complex.

**Comment by DanielEFrampton** [comment]
Updated issue description after discussion with @rer7891 and others; we'll be attempting to deal with the module/mod issue on the back-end instead of FE.
